name: aviz
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  dio: ^5.8.0+1
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_spinkit: ^5.2.1
  logger: ^2.5.0
  flutter_otp_text_field: ^1.4.0+2
  shared_preferences: ^2.5.1
  skeletonizer: ^1.4.3
  cached_network_image: ^3.4.1
  fluttertoast: ^8.2.12
  flutter_hooks: ^0.21.2
  rxdart: ^0.28.0
  connectivity_plus: ^6.1.3
  flutter_localization: ^0.3.2
  intl: ^0.19.0
  flutter_svg: ^2.0.17
  percent_indicator: ^4.2.5
  dotted_border: ^2.1.0
  flutter_osm_plugin: ^1.3.7
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Shabnam
      fonts:
        - asset: assets/fonts/Shabnam-FD.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

